steps:
  # 1단계: 필요한 라이브러리 설치 (npm install)
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # 2단계: 소스 코드를 웹 파일로 변환 (npm run build)
  # 이 과정이 끝나면 프로젝트에 'dist' 폴더가 생깁니다.
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # 3단계: 빌드된 'dist' 폴더의 파일들을 Firebase로 업로드
  - name: 'gcr.io/cloud-builders/firebase'
    args: ['deploy', '--project', 'rpg-trade-game', '--only', 'hosting']
