steps:
  # 1단계: 라이브러리 설치 (캐시 없이 클린 설치)
  - name: 'gcr.io/cloud-builders/npm' # 버전을 명시해주는 것이 안전합니다.
    args: ['install']

  # 2단계: 빌드 실행 (메모리 제한을 풀고 타입 체크는 생략)
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # 3단계: Firebase 배포
  - name: 'us-docker.pkg.dev/firebase-cli/us/firebase'
    args: ['deploy', '--project', 'rpg-trade-game', '--only', 'hosting']

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY