steps:
  # 1단계: 라이브러리 설치 (캐시 없이 클린 설치)
  - name: 'gcr.io/cloud-builders/npm' # 버전을 명시해주는 것이 안전합니다.
    args: ['install']

  # 2단계: 빌드 실행 (메모리 제한을 풀고 타입 체크는 생략)
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # 메모리 할당량을 늘려주고 빌드만 수행 (tsc 생략)
        export NODE_OPTIONS=--max-old-space-size=2048
        npm run build || ./node_modules/.bin/vite build

  # 3단계: Firebase 배포
  - name: 'gcr.io/cloud-builders/firebase'
    args: ['deploy', '--project', 'rpg-trade-game', '--only', 'hosting']

options:
  logging: NONE